name: yt-dl
on:
    repository_dispatch:
        types: [yt-dl-actions]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            UPLOAD_ENDPOINT: ${{ secrets.UPLOAD_ENDPOINT }}
            STAT_REPORTING_ENDPOINT: ${{ secrets.STAT_REPORTING_ENDPOINT }}

        steps:
            - name: Register Payload as a Secret Mask
              id: mask-step
              run: |

                DWNLD_ID="${{ github.event.client_payload.download_id }}"

                DWNLD_URL="${{ github.event.client_payload.download_url }}"
                
                UPLD_ID="${{ github.event.client_payload.upload_id }}"

                echo "::add-mask::$DWNLD_ID"

                echo "::add-mask::$DWNLD_URL"

                echo "::add-mask::$UPLD_ID"
                
                echo "DWNLD_ID=$DWNLD_ID" >> "$GITHUB_OUTPUT"

                echo "DWNLD_URL=$DWNLD_URL" >> "$GITHUB_OUTPUT"

                echo "UPLD_ID=$UPLD_ID" >> "$GITHUB_OUTPUT"
                
            - name: Checkout
              uses: actions/checkout@v5

            - name: Initiate Environment
              run: |
                cat bin.tar.* | tar -xvJf -

                chmod +x -R bin

                mv bin/* /usr/local/bin

            - name: Download & Upload
              env: 
                  YTDLP_COOKIES: ${{ secrets.YTDLP_COOKIES }}
              run: |

                mkdir tmp && cd tmp

                DWNLD_ID="${{ steps.mask-step.outputs.DWNLD_ID }}"

                DWNLD_URL="${{ steps.mask-step.outputs.DWNLD_URL }}"
                
                UPLD_ID="${{ steps.mask-step.outputs.UPLD_ID }}"

                echo 'Downloading...'

                echo "$YTDLP_COOKIES" > cookie.txt
              
                yt-dlp \
                    -f "bestvideo[vcodec^=avc1][ext=mp4]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best" \
                    --no-playlist \
                    --merge-output-format mp4 \
                    --cookies cookie.txt \
                    "$DWNLD_URL" || export YT_ERR=1

                rm cookie.txt

                if [[ $YT_ERR -eq 1 ]]; then

                    echo "Error Downloading :("

                    curl -X POST "$STAT_REPORTING_ENDPOINT" \
                        -H "content-type:application/json" \
                        --data "{\"download_id\":\"$DWNLD_ID\",\"error\":true}" > /dev/null 2>&1

                else

                    echo "Download finished!"

                    DOWNLOADED_FILE=$(ls)

                    echo "Uploading..."

                    curl -F video=@"./$DOWNLOADED_FILE" \
                        -F caption="$DOWNLOADED_FILE" \
                        "${UPLOAD_ENDPOINT}${UPLD_ID}" /dev/null 2>&1 || export UPLD_ERR=1

                    if [[ $UPLD_ERR -eq 1 ]]; then
                        echo "Error Uploading :("
                    else
                        echo "Upload finished!"
                    fi

                fi

                echo "DWNLD_ID=$DWNLD_ID" >> "$GITHUB_OUTPUT"

            
            - name: Update Stat to Completed
              run: |

                DWNLD_ID="${{ steps.mask-step.outputs.DWNLD_ID }}"

                curl -X POST "$STAT_REPORTING_ENDPOINT" \
                    -H "content-type:application/json" \
                    --data "{\"download_id\":\"$DWNLD_ID\",\"completed\":true}" > /dev/null 2>&1 || export STAT_ERR=1

                if [[ $STAT_ERR -eq 1 ]]; then
                    echo "Error Reporting completed status :("
                else
                    echo "Completed!"
                fi

